version: 2.1

orbs: 
  flutter: circleci/flutter@2.0.2
  macos: circleci/macos@2.4.0
  gcp-cli: circleci/gcp-cli@3.1.1

commands:

  inject-netrc-credentials:
    steps:
      - run:
          name: Configure .netrc
          command: |
            echo "machine api.mapbox.com login mapbox password ${SDK_REGISTRY_TOKEN}" >> ~/.netrc
            chmod 0600 ~/.netrc
  
  setup-gcloud:
    steps:
      - gcp-cli/setup:
          version: 449.0.0
          gcloud_service_key: GCLOUD_SERVICE_ACCOUNT_JSON

  add-mapbox-submodules-key:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "9d:db:07:0b:62:81:11:c3:46:21:8e:fa:51:99:80:2d"

jobs:
  dummy:
    executor: helsinki-samsung_s22
    steps:
      - run:
          name: "Dummy"
          command: echo "Hello world"
  build-android:
    parameters:
      workspace-path:
        type: string
        default: example/build/app/outputs/apk
    docker:
      - image: cimg/android:2022.09
    resource_class: xlarge
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          version: 3.13.6
          app-dir: example
      - run:
          name: ktlint
          working_directory: example/android
          command: ./gradlew ktlint
      - run:
          name: unit test
          command: flutter test test
      - run:
          name: "Build Android integration tests"
          working_directory: example/android
          command: |
            flutter build apk
            ./gradlew app:assembleAndroidTest
            ./gradlew app:assembleDebug -Ptarget=integration_test/all_test.dart -Pdart-defines="$(echo -n "ACCESS_TOKEN=$MAPBOX_ACCESS_TOKEN" | base64 -w 0)"
      - persist_to_workspace:
          root: << parameters.workspace-path >>
          paths:
            - debug/app-debug.apk
            - androidTest/debug/app-debug-androidTest.apk

  run-android-tests-firebase:
    parameters:
      workspace-path:
        type: string
        default: example/build/app/outputs/apk
    executor: firebase-test-runner
    steps:
      - attach_workspace:
          at: << parameters.workspace-path >>
      - setup-gcloud
      - run:
          name: "Run Android integration tests on Firebase"
          no_output_timeout: 20m
          command: |
            gcloud firebase test android run --type instrumentation \
              --app << parameters.workspace-path >>/debug/app-debug.apk \
              --test << parameters.workspace-path >>/androidTest/debug/app-debug-androidTest.apk \
              --timeout 5m \
              --device model=oriole,version=33,locale=en,orientation=portrait \
              --results-dir=result_dir \
              --use-orchestrator \
              --num-flaky-test-attempts 3     
                         
  build-ios:
    parameters:
      workspace-path:
        type: string
        default: example/build/output
    executor: macos-xcode-latest
    steps:
      - checkout
      - inject-netrc-credentials
      - add-mapbox-submodules-key
      - macos/install-rosetta
      - run:
          name: Use activesupport 7.0.8 so that Cocoapods works
          command: |
            # activesupport was pinned because of Cocoapods being incompatible with active support 7.0.10,
            # more details here - https://github.com/CocoaPods/CocoaPods/issues/12081
            # allegedly, this issue is resolved in https://github.com/CocoaPods/CocoaPods/pull/12082,
            # pinning can be removed after the above fix is released
            gem uninstall activesupport --version '>= 7.0.8' --ignore-dependencies
            gem install activesupport --version '7.0.8'
      - flutter/install_sdk_and_pub:
          version: 3.13.6
          app-dir: example
      - flutter/install_ios_pod:
          app-dir: example
      - run:
          name: swiftlint
          working_directory: ios
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install swiftlint; swiftlint lint --strict
      - run:
          name: unit test
          command: flutter test test
      - run:
          name: "Build iOS integration tests"
          command: |
            pushd example

            # required to init configs that pass environment variables to fastlane later
            flutter build ios integration_test/all_test.dart \
              --release --dart-define=ACCESS_TOKEN=${MAPBOX_ACCESS_TOKEN}

            popd # to repo root

            bundle exec fastlane build_examples_tests
      - persist_to_workspace:
          root: << parameters.workspace-path >>
          paths:
            - build_products.zip

  run-ios-tests-firebase:
    parameters:
      workspace-path:
        type: string
        default: example/build/output
    executor: firebase-test-runner
    steps:
      - attach_workspace:
          at: << parameters.workspace-path >>
      - setup-gcloud
      - run:
          name: "Run iOS integration tests on Firebase"
          no_output_timeout: 20m
          command: |
            gcloud firebase test ios run \
              --test << parameters.workspace-path >>/build_products.zip \
              --device model=iphone8,version=15.7 \
              --timeout 5m \
              --num-flaky-test-attempts 3



workflows:
  build:
    jobs:
      - dummy
      - build-android
      - run-android-tests-firebase:
          requires:
            - build-android
      - build-ios
      - run-ios-tests-firebase:
          requires:
            - build-ios

executors:
  macos-xcode-latest:
    resource_class: macos.m1.medium.gen1
    macos:
      xcode: 15.0.0
  firebase-test-runner:
    resource_class: small
    docker:
      - image: cimg/python:3.7
  helsinki-iphone_7:
      resource_class: mapbox/helsinki-iphone_7
      machine: true
  helsinki-iphone_12:
      resource_class: mapbox/helsinki-iphone_12
      machine: true
  helsinki-google_pixel_4_xl:
      resource_class: mapbox/helsinki-google_pixel_4_xl
      machine: true
  helsinki-google_pixel_5:
      resource_class: mapbox/helsinki-google_pixel_5
      machine: true
  helsinki-google_pixel_6:
      resource_class: mapbox/helsinki-google_pixel_6
      machine: true
  helsinki-motorola_moto_g22:
      resource_class: mapbox/helsinki-motorola_moto_g22
      machine: true
  helsinki-samsung_s22:
      resource_class: mapbox/helsinki-samsung_s22
      machine: true
  helsinki-samsung_galaxy_a12:
      resource_class: mapbox/helsinki-samsung_galaxy_a12
      machine: true
  helsinki-bmw_bench:
      resource_class: mapbox/helsinki-bmw_bench
      machine: true
  helsinki-linux_x86_64_small:
      resource_class: mapbox/helsinki-linux_x86_64_small
      machine: true
  helsinki-21mm_pana_t_entry_8inch:
      resource_class: mapbox/helsinki-21mm_pana_t_entry_8inch
      machine: true
  helsinki-24mm_pana_t_prem_105inch_na:
      resource_class: mapbox/helsinki-24mm_pana_t_prem_105inch_na
      machine: true
  helsinki-24mm_pana_t_prem_123inch_na:
      resource_class: mapbox/helsinki-24mm_pana_t_prem_123inch_na
      machine: true
  helsinki-24mm_pana_t_prem_8inch_na:
      resource_class: mapbox/helsinki-24mm_pana_t_entry_8inch_na
      machine: true
  helsinki-24mm_pana_t_entry_105inch_na:
      resource_class: mapbox/helsinki-24mm_pana_t_entry_105inch_na
      machine: true
  helsinki-24mm_pana_l_entry_105inch_na:
      resource_class: mapbox/helsinki-24mm_pana_l_entry_105inch_na
      machine: true
  helsinki-24mm_dten_t_entry_8inch_na:
      resource_class: mapbox/helsinki-24mm_dten_t_entry_8inch_na
      machine: true
  helsinki-24mm_dten_t_entry_105inch_na:
      resource_class: mapbox/helsinki-24mm_dten_t_entry_105inch_na
      machine: true
  helsinki-24mm_dten_t_prem_105inch_na:
      resource_class: mapbox/helsinki-24mm_dten_t_prem_105inch_na
      machine: true
