name: mapbox_maps_flutter_web
description: A Flutter plugin for integrating Mapbox gl-js in flutter web application.
version: 0.4.1
homepage: https://github.com/mapbox/mapbox-maps-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  enum_to_string: ^2.0.1
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.5
  turf: ^0.0.7
  typed_data: ^1.3.0
  # TODO is 0.6.6 possible? 
  js: ^0.6.4
  plugin_platform_interface: ^2.0.0
  mapbox_maps_flutter_platform_interface:
    path: ../mapbox_maps_flutter_platform_interface
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.19.0
  pigeon: 3.2.3

flutter:
  plugin:
    platforms:
      web:
        pluginClass: MapboxMapsFlutterPlugin
        fileName: mapbox_maps_flutter_plugin_web.dart

